services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ecommerce-ai

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest

    container_name: ecommerce-qdrant

    ports:
      - "6333:6333"

    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: